name = "beach-proxy"
main = "worker.js"
compatibility_date = "2026-09-01"
[triggers]
crons = ["0 */6 * * *"]
name = "beach-proxy"
main = "worker.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "TRIPS_DB"
database_name = "beach-fishing-trips"
database_id = "63143fbc-1f35-443a-be6f-d62eb7ca90f3"
